server:
  port: 8084

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    redis:
      time-to-live: 5m

user-service:
  url: http://localhost:8081/api/users
product-service:
  url: http://localhost:8082/api/products
inventory-service:
  url: http://localhost:8083/api/inventory
payment-service:
  url: http://localhost:8085/api/payments